name: lottom

services:
  app:
    image: lottom:latest
    container_name: lottom-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8150:80"
    environment:
      - POSTGRES_USERNAME=test_pg_user
      - POSTGRES_PASSWORD=test_pg_passwd
      - POSTGRES_ADDRESS=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE_NAME=test_pg_master
      - COOKIEKEY=P31YCowDBtOOxe+YAQxkibdcDOVRyMhXEMe4LhFIEkHoMIT5P2z6Ii7xsuCLqhAVM6uaCrqJEJtm+PVaKVpakg==

  db:
      image: postgres:18-alpine
      container_name: lottom-db
      restart: unless-stopped
      ports:
        - "5432"
      environment:
        POSTGRES_USER: test_pg_user
        POSTGRES_PASSWORD: test_pg_passwd
        POSTGRES_DB: test_pg_master
      volumes:
        - data:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U test_pg_user -d test_pg_master"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  data:
